secrets:
  - id: username_password_test
    kind: UsernamePassword
    description: "UsernamePassword description"
    secretKeyRef:
      username: username_password_test_username
      password: username_password_test_password

  - id: openshift_oauth_token_test
    kind: OpenShiftOAuthToken
    description: "OpenShiftOAuthToken description"
    secretKeyRef:
      token: openshift_oauth_token_test_token

  - id: openshift_username_password_test
    kind: OpenShiftUsernamePassword
    description: "OpenShiftUsernamePassword description"
    secretKeyRef:
      username: openshift_username_password_test_username
      password: openshift_username_password_test_password

  - id: ssh_username_private_key_test
    kind: SshUsernamePrivateKey
    description: "SshUsernamePrivateKey description"
    secretKeyRef:
      username: ssh_username_private_key_test_username
      private_key: ssh_username_private_key_test_private_key
      passphrase: ssh_username_private_key_test_passphrase

  - id: secret_text_test
    kind: SecretText
    description: "SecretText description"
    secretKeyRef:
      secret: secret_text_test_secret

#  - id: docker_host_cert_auth_test
#    kind: DockerHostCertificateAuth
#    description: "DockerHostCertificateAuth description"
#    secretKeyRef:
#      clientKey: docker_host_cert_auth_test_clientKey
#      clientCertificate: docker_host_cert_auth_test_clientCertificate
#      serverCACertificate: docker_host_cert_auth_test_serverCACertificate
# todo
#  - id: certificate_test
#    kind: Certificate
#     description: "Certificate description"
#    secretKeyRef:
#      certificate: secret_name
#      password: secret_name
